name: 'Artifacts Cleanup'
on:
  push:
    paths:
     - '.github/workflows/cleanup.yml'
  schedule:
    - cron: '0 9 * * *' # every night at 9 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days # Set this to 0 to delete all artifacts